### ISSUE TITLE
Create `Company` and `Text` object

### ISSUE THREAD

**Issue by erfangc** [erfangc/bdozer-ai#1]
# Storage

Elasticsearch

# `Company` schema

```yaml
cik: str
products:
 - p1
 - p2
topics:
 - t1
 - t2
competitors:
 - cik1
 - cik2
suppliers:
 - cik1
 - cik2
# once we finished parsing/scoring and storing TenKSentence(s)
# we run Q&A NLP engines to find the answer to each question here
# we may choose to smooth over or average answers
riskFactors:
 - sentence1
 - sentence2
 - sentence3
biggestCosts:
 - sentence1
 - sentence2
lastUpdated: yyyy-MM-dd:hh:mm:ss
```

`Text` Schema
```
textId: xxxxx-xxxxxxxx
type: 10-K
source: string
author: string
cik: string
ash: string
asOfDate: yyyy-MM-dd
lastUpdated: yyyy-MM-dd:hh:mm:ss
docUrl: https://sec.gov/blahblah.html
sentence: Some full-sentence we extracted
namedEntities:
 - type: person
 - value: Bob Jones
# thesse "scores" are cross_encoder scores against questions we ask about 
# every firm on each sentence
hasProductScore: 1.222
hasCompetitorScore: 23.22
hasRiskFactorScore: 22.222
hasCostScore: 222.22
# zero-shot classification labels
topics:
 - esg
 - inflation
 - covid
 - gas prices
 - war
 ```
